apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: nginx 
volumes:
  - name: app-storage
    emptyDir: {}
spec:
 containers:
 - name: app1 
   image: supergiantkir/animals:bear 
   ports: 
   - containerPort: 80
   volumeMounts:
    - name: app-storage
      mountPath: /storage

 - name: app2
   image: yanivomc/spring-music:latest
   ports: 
   - containerPort: 80
   volumeMounts:
    - name: app-storage
      mountPath: /storage
