apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  selector:
    matchLabels:
      app: spring-music

  replicas: 2 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0

  template: 
    metadata:
      labels:
        app: spring-music
    spec:
      containers:
      - name: springmusic
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
